spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
cloud:
  aws:
    s3:
      bucket: bidbid
      dir: /image
      region:
        static: ap-northeast-2
      default-path: images

    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
